apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-website
  labels:
    app: react-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-website
  template:
    metadata:
      labels:
        app: react-website
    spec:
      containers:
        - name: react-website
          image: my-react-app:latest   # Your Docker image name
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: react-website-service
spec:
  type: NodePort
  selector:
    app: react-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080   # Access the website via localhost:30080
